### ISSUE TITLE
no hosts match

### ISSUE THREAD

**Issue by dodizzle** [rfrail3/grafana-dashboards#1]
I was able to load your dashboard after changing the datasource name but cannot get any hosts to appear.
I verified that all of my other dashboards work where the label="Host:" matches the name="host" which I also changed.
How can I debug this to get your dashboard to work?

**Comment by rfrail3** [comment]
Hi dodizzle,

What is the result of the following query in your Prometheus datasource?

node_boot_time{job="node-exporter"}

**Comment by RyanHartje** [comment]
Might want to indicate that people need a node-exporter job in a README.md.
The Node Network dash also is able to grab hosts from all jobs I believe:
https://grafana.com/dashboards/1856

It may be a good example if you want to go in that direction in the future.

**Comment by rfrail3** [comment]
Thanks for the info, I just remove the job requirement as Node Network do.
