### ISSUE TITLE
No values shown

### ISSUE THREAD

**Issue by mar1ged** [rfrail3/grafana-dashboards#10]
I have a setup with node_exporter 0.15.2, Prometheus 2.1 and Grafana 4.6.3
I am not able to display any values.

When I open Prometheus, it is able to show values from node_exporter. Other dashboards work too.

![novalues](https://user-images.githubusercontent.com/16045549/36662923-40a279be-1ae0-11e8-96f9-8e5fe71f6024.png)

**Comment by mar1ged** [comment]
Shame on me ... I used the Query Inspector and found out that no data was passed between Grafana and Prometheus. The reason for this was a firewall rule.

**Comment by anaganisk** [comment]
@mar1ged can you tell me what firewall rule was meddling? I have a similar issue
