### ISSUE TITLE
Gauges "CPU System Load" of Node Exporter Full 0.16 dashboard appearing red with values > 100%

### ISSUE THREAD

**Issue by greg-junkietech** [rfrail3/grafana-dashboards#14]
I am running Node Exporter 0.16.0-rc.2 on such Linux system
`Linux XXXXXXXXXXX 3.10.0-693.11.6.el7.x86_64 GNU/Linux`
producing such metrics: [NodeExporter_Metrics.txt](https://github.com/rfrail3/grafana-dashboards/files/1970199/NodeExporter_Metrics.txt)

The grafana dashboard `Node Exporter Full 0.16` shows me gauges "CPU System Load" appearing red with values > 100%:
![image](https://user-images.githubusercontent.com/8457529/39567870-a3dd1336-4ec0-11e8-9e8b-f20779a30e1d.png)
How is it to interpret?

**Comment by rfrail3** [comment]
Yes because as you have 18.16 process trying to get the running state at the same time and you only have 8 cores for their execution, the system is overloaded in 227%.

**Comment by hemanth-reckonsys** [comment]
@rfrail3 how to create that(system load 1m avg) particular card ?
