### ISSUE TITLE
Is it possible to get Top URLs by Response Code?

### ISSUE THREAD

**Issue by shoaibjdev** [rfrail3/grafana-dashboards#16]
Hi,

For the HAProxy grafana dashboard, is it possible to build a graph for Top URL's (http_request) accessed and their response codes?
From the metrics gathered from Prometheus I can't seem to find the http_request being captured as part of stats. How can this be enabled?

**Comment by rfrail3** [comment]
Please, for that question, the right place in where you can find a valid response is inside the [Prometheus Haproxy Exporter Project](https://github.com/prometheus/haproxy_exporter).
