### ISSUE TITLE
node-exporter-full: templating variable

### ISSUE THREAD

**Issue by LukeHandle** [rfrail3/grafana-dashboards#17]
Hey there, a more stable label for templating off might be `node_exporter_build_info`. There is a version label on that as well which might be useful :man_shrugging:

**Comment by rfrail3** [comment]
Hi Luke,

What label do you want to substitute? What are the problems that you have with the actual dashboard?

Thanks,

**Comment by LukeHandle** [comment]
Hey Ricardo,
I meant the `node_boot_time` in the `label_values(node_boot_time, job)` (and other templating variables). I noticed you changed this with the recent node_export update, but the `node_exporter_build_info` might prove more stable between versions.

For better or worse, it would also result in older versions still being listed in the template dropdown.

Thanks!

**Comment by rfrail3** [comment]
It can have more sense, thanks!
