### ISSUE TITLE
SWAP Used display not correct

### ISSUE THREAD

**Issue by opskumu** [rfrail3/grafana-dashboards#2]
![Memory Basic](https://grafana.com/api/dashboards/1860/images/1182/image)

Memory Basic, if display `SWAP Used` only，it's correct.  But, if display all, `SWAP Used` equal `RAM Total`.

Thanks.

**Comment by rfrail3** [comment]
It was at top because I tried to copy the munin style, for example:

![image](https://cloud.githubusercontent.com/assets/215429/26095507/328b2a7c-3a1e-11e7-8019-4f1b5f3f6b2b.png)

But you are right, it can cause confusion.

**Comment by opskumu** [comment]
Ok, i see :), Thanks.
