### ISSUE TITLE
no data on dashboards

### ISSUE THREAD

**Issue by zhoffice** [rfrail3/grafana-dashboards#22]
This is my yml config, what is the problem?
scrape_configs:
  \- job_name: node
    static_configs:
      \- targets: ['192.168.0.17:9100']
        labels:
          instance: 192.168.0.17:9100

**Comment by kskewes** [comment]
Are you using Node Exporter 0.16.0 ?
Can you see the various metrics in Prometheus (not Grafana)?

**Comment by rfrail3** [comment]
Please, use one of the latest releases. Prometheus usually push breaking changes between releases and sometimes is difficult to keep working the dashboards between them.
