### ISSUE TITLE
图没有数据问题（即启用collector的方法）

### ISSUE THREAD

**Issue by xuezm01** [rfrail3/grafana-dashboards#24]
我是在kubernets 上部署的node-exporter，请问一下启用 netstat vmstat ，是在镜像启动添加args 参数吗 ？ 我的写法为 
      - image: prom/node-exporter:latest
        imagePullPolicy: IfNotPresent
        name: prometheus-node-exporter
        args:
          - --collector.netstat.fields=(.*) --collector.vmstat.fields=(.*)  --collector.interrupts

启动没有问题，但是图还是没有补全。请执教

**Comment by rfrail3** [comment]
Sorry but I don't understand your message.
