### ISSUE TITLE
count_scalar gone from prometheus 1.8.2

### ISSUE THREAD

**Issue by rlucian** [rfrail3/grafana-dashboards#25]
In prometheus 1.8.2's change log， it said that the function count_scalar is removed，so, some dashboards which use this function may cause an error. which function i can use to replace? maybe 'absent'?

error thrown is "grafana unknown function with name count_scalar" for one of the graphs.
solution is to replace count_scalar(...) with scalar(count(...))
credit: https://github.com/grafana/grafana-plugins/issues/45

**Comment by rfrail3** [comment]
The solution was merged time ago. Thanks for the report.
