### ISSUE TITLE
Multiple Series Error

### ISSUE THREAD

**Issue by viewty** [rfrail3/grafana-dashboards#3]
Hi, I'm having a bit of a problem. I've imported the dashboard but many of the graphs show error "Multiple Series Error" so not loading any data

![screen shot 2017-07-11 at 15 14 58](https://user-images.githubusercontent.com/2039900/28067883-c4e821d2-664b-11e7-8bd9-e7db6b7de6c6.png)

I haven't changed anything, basic installed of prometheus, grafana and then imported your dashboard.

**Comment by arj22** [comment]
I had this error when I was receiving metrics from both Consul targets and static targets. The moment I turned off Consul, the error disappeared.

**Comment by dgedia** [comment]
I'm facing the exact same error as well. Any suggestions would be really appreciated. Thanks

**Comment by DevOps-Dad** [comment]
+1 I am also seeing the same issue.  Any insight would be appreciated.  Thanks!!

**Comment by rfrail3** [comment]
I just upload a new version with some improvementes, it is possible that this is already fixed.

**Comment by dgedia** [comment]
Thanks @rfrail3 . The issue seems to be fixed in the recent upload (Release 11). Much appreciated!

**Comment by DevOps-Dad** [comment]
Yes, fixed for me as well.  Thanks!!!

**Comment by yongsr** [comment]
I am having this same issue, it was working fine for few days and now gave me the error, however newly added server is fine though

**Comment by pawansinha0612** [comment]
i am also facing this issue but what versions i need to change to work ?
