### ISSUE TITLE
Multi Series Error on Node Exporter Full

### ISSUE THREAD

**Issue by yongsr** [rfrail3/grafana-dashboards#31]
I am using Node Exporter Full on my Prometheus setup, everything was working fine, until today out of no reason, some graphs gave me Multi Series Error, but on newly added server, it is working fine.

![image](https://user-images.githubusercontent.com/46220131/53325545-884c1380-391e-11e9-87c6-ddea8c35d2ca.png)

**Comment by mikelitka** [comment]
I am seeing the same thing. Please see below:

Multiple Series Error
Metric query returns 2 series. Single Stat Panel expects a single series.

Response:
[{"datapoints":[[0.03,1559673900000],[0.15,1559674800000],[null,1559675700000],[null,1559676600000],[null,1559677500000],[null,1559678400000],[null,1559679300000],[null,1559680200000],[null,1559681100000],[null,1559682000000],[null,1559682900000],[null,1559683800000],[null,1559684700000],[null,1559685600000],[null,1559686500000],[null,1559687400000],[null,1559688300000],[null,1559689200000],[null,1559690100000],[null,1559691000000],[null,1559691900000],[null,1559692800000],[null,1559693700000],[null,1559694600000],[null,1559695500000],[null,1559696400000],[null,1559697300000],[null,1559698200000],[null,1559699100000],[null,1559700000000],[null,1559700900000],[null,1559701800000],[null,1559702700000],[null,1559703600000],[null,1559704500000],[null,1559705400000],[null,1559706300000],[null,1559707200000],[null,1559708100000],[null,1559709000000],[null,1559709900000],[null,1559710800000],[null,1559711700000],[null,1559712600000],[null,1559713500000],[null,1559714400000],[null,1559715300000],[null,1559716200000],[null,1559717100000],[null,1559718000000],[null,1559718900000],[null,1559719800000],[null,1559720700000],[null,1559721600000],[null,1559722500000],[null,1559723400000],[null,1559724300000],[null,1559725200000],[null,1559726100000],[null,1559727000000],[null,1559727900000],[null,1559728800000],[null,1559729700000],[null,1559730600000],[null,1559731500000],[null,1559732400000],[null,1559733300000],[null,1559734200000],[null,1559735100000],[null,1559736000000],[null,1559736900000],[null,1559737800000],[null,1559738700000],[null,1559739600000],[null,1559740500000],[null,1559741400000],[null,1559742300000],[null,1559743200000],[null,1559744100000],[null,1559745000000],[null,1559745900000],[null,1559746800000],[null,1559747700000],[null,1559748600000],[null,1559749500000],[null,1559750400000],[null,1559751300000],[null,1559752200000],[null,1559753100000],[null,1559754000000],[null,1559754900000],[null,1559755800000],[null,1559756700000],[null,1559757600000],[null,1559758500000],[null,1559759400000],[null,1559760300000],[null,1559761200000]],"label":"node_load1{group=\"av\",instance=\"<redacted>:9100\",job=\"linux\"}","id":"node_load1{group=\"av\",instance=\"<redacted>:9100\",job=\"linux\"}","alias":"node_load1{group=\"av\",instance=\"<redacted>:9100\",job=\"linux\"}","aliasEscaped":"node_load1{group="av",instance="<redacted>:9100",job="linux"}","bars":{},"stats":{"total":0.18,"max":0.15,"min":0.03,"logmin":0.03,"avg":0.09,"current":null,"first":0.03,"delta":0.12,"diff":null,"range":0.12,"timeStep":900000,"count":98},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1559673900000,0.03],[1559674800000,0.15],[1559675700000,null],[1559676600000,null],[1559677500000,null],[1559678400000,null],[1559679300000,null],[1559680200000,null],[1559681100000,null],[1559682000000,null],[1559682900000,null],[1559683800000,null],[1559684700000,null],[1559685600000,null],[1559686500000,null],[1559687400000,null],[1559688300000,null],[1559689200000,null],[1559690100000,null],[1559691000000,null],[1559691900000,null],[1559692800000,null],[1559693700000,null],[1559694600000,null],[1559695500000,null],[1559696400000,null],[1559697300000,null],[1559698200000,null],[1559699100000,null],[1559700000000,null],[1559700900000,null],[1559701800000,null],[1559702700000,null],[1559703600000,null],[1559704500000,null],[1559705400000,null],[1559706300000,null],[1559707200000,null],[1559708100000,null],[1559709000000,null],[1559709900000,null],[1559710800000,null],[1559711700000,null],[1559712600000,null],[1559713500000,null],[1559714400000,null],[1559715300000,null],[1559716200000,null],[1559717100000,null],[1559718000000,null],[1559718900000,null],[1559719800000,null],[1559720700000,null],[1559721600000,null],[1559722500000,null],[1559723400000,null],[1559724300000,null],[1559725200000,null],[1559726100000,null],[1559727000000,null],[1559727900000,null],[1559728800000,null],[1559729700000,null],[1559730600000,null],[1559731500000,null],[1559732400000,null],[1559733300000,null],[1559734200000,null],[1559735100000,null],[1559736000000,null],[1559736900000,null],[1559737800000,null],[1559738700000,null],[1559739600000,null],[1559740500000,null],[1559741400000,null],[1559742300000,null],[1559743200000,null],[1559744100000,null],[1559745000000,null],[1559745900000,null],[1559746800000,null],[1559747700000,null],[1559748600000,null],[1559749500000,null],[1559750400000,null],[1559751300000,null],[1559752200000,null],[1559753100000,null],[1559754000000,null],[1559754900000,null],[1559755800000,null],[1559756700000,null],[1559757600000,null],[1559758500000,null],[1559759400000,null],[1559760300000,null],[1559761200000,null]]},{"datapoints":[[null,1559673900000],[null,1559674800000],[0.03,1559675700000],[0.06,1559676600000],[0.04,1559677500000],[0.21,1559678400000],[0.11,1559679300000],[0.14,1559680200000],[0,1559681100000],[0.01,1559682000000],[0.15,1559682900000],[0.05,1559683800000],[0.02,1559684700000],[0.08,1559685600000],[0.01,1559686500000],[0.05,1559687400000],[0.03,1559688300000],[0.08,1559689200000],[0.14,1559690100000],[0.09,1559691000000],[0.16,1559691900000],[0.07,1559692800000],[0.15,1559693700000],[0.08,1559694600000],[0.08,1559695500000],[0.04,1559696400000],[0.22,1559697300000],[0.12,1559698200000],[0.08,1559699100000],[0.01,1559700000000],[0.13,1559700900000],[0.25,1559701800000],[0.01,1559702700000],[0.12,1559703600000],[0.14,1559704500000],[0.07,1559705400000],[0.03,1559706300000],[0.1,1559707200000],[0.05,1559708100000],[0.1,1559709000000],[0.02,1559709900000],[0.1,1559710800000],[0.02,1559711700000],[0.12,1559712600000],[0.25,1559713500000],[0.06,1559714400000],[0.18,1559715300000],[0.18,1559716200000],[0.06,1559717100000],[0.02,1559718000000],[0.02,1559718900000],[0.1,1559719800000],[0.04,1559720700000],[0.03,1559721600000],[0.07,1559722500000],[0.08,1559723400000],[0.11,1559724300000],[0.08,1559725200000],[0.17,1559726100000],[0.08,1559727000000],[0.1,1559727900000],[0.08,1559728800000],[0.06,1559729700000],[0.08,1559730600000],[0.07,1559731500000],[0.03,1559732400000],[0.06,1559733300000],[0.12,1559734200000],[0.02,1559735100000],[0.15,1559736000000],[0.06,1559736900000],[0.08,1559737800000],[0.11,1559738700000],[0.06,1559739600000],[0.01,1559740500000],[0.09,1559741400000],[0.11,1559742300000],[0.12,1559743200000],[0.05,1559744100000],[0.05,1559745000000],[0.01,1559745900000],[0.1,1559746800000],[0.07,1559747700000],[0.07,1559748600000],[0.03,1559749500000],[0.08,1559750400000],[0.11,1559751300000],[0.08,1559752200000],[0.06,1559753100000],[0.01,1559754000000],[0.05,1559754900000],[0.01,1559755800000],[0.07,1559756700000],[0.1,1559757600000],[0.05,1559758500000],[0,1559759400000],[0.07,1559760300000],[null,1559761200000]],"label":"node_load1{instance=\"<redacted>:9100\",job=\"linux\",location=\"av\",node_exporter=\"18\"}","id":"node_load1{instance=\"<redacted>:9100\",job=\"linux\",location=\"av\",node_exporter=\"18\"}","alias":"node_load1{instance=\"<redacted>:9100\",job=\"linux\",location=\"av\",node_exporter=\"18\"}","aliasEscaped":"node_load1{instance="<redacted>:9100",job="linux",location="av",node_exporter="18"}","bars":{},"stats":{"total":7.579999999999997,"max":0.25,"min":0,"logmin":0.01,"avg":0.0797894736842105,"current":0.07,"first":0.03,"delta":4.14,"diff":0.04000000000000001,"range":0.25,"timeStep":900000,"count":98},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1559673900000,null],[1559674800000,null],[1559675700000,0.03],[1559676600000,0.06],[1559677500000,0.04],[1559678400000,0.21],[1559679300000,0.11],[1559680200000,0.14],[1559681100000,0],[1559682000000,0.01],[1559682900000,0.15],[1559683800000,0.05],[1559684700000,0.02],[1559685600000,0.08],[1559686500000,0.01],[1559687400000,0.05],[1559688300000,0.03],[1559689200000,0.08],[1559690100000,0.14],[1559691000000,0.09],[1559691900000,0.16],[1559692800000,0.07],[1559693700000,0.15],[1559694600000,0.08],[1559695500000,0.08],[1559696400000,0.04],[1559697300000,0.22],[1559698200000,0.12],[1559699100000,0.08],[1559700000000,0.01],[1559700900000,0.13],[1559701800000,0.25],[1559702700000,0.01],[1559703600000,0.12],[1559704500000,0.14],[1559705400000,0.07],[1559706300000,0.03],[1559707200000,0.1],[1559708100000,0.05],[1559709000000,0.1],[1559709900000,0.02],[1559710800000,0.1],[1559711700000,0.02],[1559712600000,0.12],[1559713500000,0.25],[1559714400000,0.06],[1559715300000,0.18],[1559716200000,0.18],[1559717100000,0.06],[1559718000000,0.02],[1559718900000,0.02],[1559719800000,0.1],[1559720700000,0.04],[1559721600000,0.03],[1559722500000,0.07],[1559723400000,0.08],[1559724300000,0.11],[1559725200000,0.08],[1559726100000,0.17],[1559727000000,0.08],[1559727900000,0.1],[1559728800000,0.08],[1559729700000,0.06],[1559730600000,0.08],[1559731500000,0.07],[1559732400000,0.03],[1559733300000,0.06],[1559734200000,0.12],[1559735100000,0.02],[1559736000000,0.15],[1559736900000,0.06],[1559737800000,0.08],[1559738700000,0.11],[1559739600000,0.06],[1559740500000,0.01],[1559741400000,0.09],[1559742300000,0.11],[1559743200000,0.12],[1559744100000,0.05],[1559745000000,0.05],[1559745900000,0.01],[1559746800000,0.1],[1559747700000,0.07],[1559748600000,0.07],[1559749500000,0.03],[1559750400000,0.08],[1559751300000,0.11],[1559752200000,0.08],[1559753100000,0.06],[1559754000000,0.01],[1559754900000,0.05],[1559755800000,0.01],[1559756700000,0.07],[1559757600000,0.1],[1559758500000,0.05],[1559759400000,0],[1559760300000,0.07],[1559761200000,null]]}]
