### ISSUE TITLE
Parameter correction for a fuly working dashboard

### ISSUE THREAD

**Issue by torstenandrecht** [rfrail3/grafana-dashboards#36]
For get a fully working dashboard, this is the right start commend. The documantation contains brackets instead of "

nohup ./node_exporter —collector.netstat.fields=“.*” --collector.vmstat.fields=“.*”  --collector.interrupts &

**Comment by rfrail3** [comment]
You are right, last releases of node-exporter decreased the number of default values on vmstat and netstat [1] and the dashbard had been already done with the prior ones.

Last commit [2] update to v0.18 node-exporter default values, so the dashboard only have these default ones.

Thanks,

[1] -https://github.com/prometheus/node_exporter/commit/499c342fed469de88a6c102d50bfc61853520d2d
[2] - https://github.com/rfrail3/grafana-dashboards/commit/445926c6eeb7e23b3e6620e7fb094fa16435d225
