### ISSUE TITLE
Network unit measure on Node Exporter Full

### ISSUE THREAD

**Issue by escanoru** [rfrail3/grafana-dashboards#37]
Hello,

Network speed is measure on bits per second not bytes. The metrics collected by node_exporter are given in bytes, for example:
`node_network_receive_bytes_total`
This needs to be multiplied by 8 to get the real value in bits.
To be more specific, the "Network Traffic Basic" has the following query:
`irate(node_network_receive_bytes_total{instance=~"$node:$port",job=~"$job"}[5m])`
This query shows the data as it's given by the node_exporter, in other words in bytes.

The query should be:
`irate(node_network_receive_bytes_total{instance=~"$node:$port",job=~"$job"}[5m])*8`

As a consequence of this, the "unit measure" to show the data in the left "Y" axis needs to be change to "bits/sec" under "data rate":
![image](https://user-images.githubusercontent.com/44711170/65206530-e9b70980-da4b-11e9-8c17-fc273f116de9.png)

**Comment by rfrail3** [comment]
You are right, it is changed on last commit.

Thanks,
