### ISSUE TITLE
HAProxy 2.0 - broken numbers

### ISSUE THREAD

**Issue by dekkerm** [rfrail3/grafana-dashboards#43]
Hi,

I am a bit curious how to read broken numbers in this dashboard.
So for example number of connections (current) = 0.133
Number of HTTP Responses, min, max and current, 0.067, 4.333, 0.067.
Why is the current connection not either 0 or 1, but 0.133?

See also the below image

![haproxy_grafana](https://user-images.githubusercontent.com/26568969/70419646-22241d80-1a66-11ea-8543-673ace8e4a25.PNG)

Regards,

Maarten

**Comment by dekke046** [comment]
Anybody???

**Comment by dragoangel** [comment]
This because they are calculated regarding timeframe
