### ISSUE TITLE
Support meaningful instance labels

### ISSUE THREAD

**Issue by candlerb** [rfrail3/grafana-dashboards#57]
When using [meaningful instance labels](https://www.robustperception.io/controlling-the-instance-label) there is only a name, and no port number, in the instance label.  Unfortunately, the existing node_exporter dashboard does not work without a port.

I suggest using the instance label directly.

Also, given that job and node are not multi-select, these can use `=` rather than `=~` for matching (more efficient, less likely to trip up on regexp metacharacters)

I've made these changes in [12486](https://grafana.com/grafana/dashboards/12486) which is a direct fork of 1860.

**Comment by rfrail3** [comment]
Thanks for update the dashboard with the work done, it helps.
