### ISSUE TITLE
Wrong value for "SWAP Used" - node-exporter FreeBSD

### ISSUE THREAD

**Issue by hbokh** [rfrail3/grafana-dashboards#59]
Besides of replacing `\"$node:$port\"` with `\"$node\"` in my personal setup, I had to get rid of the `*100` in this line.
https://github.com/rfrail3/grafana-dashboards/blob/master/prometheus/node-exporter-freebsd.json#L399

"SWAP Used"  would show 265%, but IRL 2,6%:

```
$ freecolor -m
Physical  : [######################.............] 63%	(2451/3846)
Swap      : [##################################.] 97%	(751/768)
```

```
$ freebsd-version
11.3-RELEASE-p10
```

**Comment by Geezabiscuit** [comment]
I resolved this by replacing node_memory_swap_in_bytes_total with node_memory_swap_size_bytes here: https://github.com/rfrail3/grafana-dashboards/blob/b5d0deeadd97b697d79855fa9408c8e18583582d/prometheus/node-exporter-freebsd.json#L430

This changes the calculation to ((used swap * 100) / swap size), giving used swap as a percentage of the maximum available swap.

**Comment by rfrail3** [comment]
Thanks, I just upload it to grafana.com too
