### ISSUE TITLE
Port must be the same for multiple targets

### ISSUE THREAD

**Issue by theodotos** [rfrail3/grafana-dashboards#6]
I noticed that if the port on all targets is not the same, the the Dashboard picks only one of them as the port and displays only that one, presenting the targets with different ports as 'no data points'

My workaround was to have a consistent node-exporter port for all hosts.

**Comment by mfominov** [comment]
@theodotos make replace from instance=~\"$node:$port\" to instance=~\"$node\"
and u can use different port on hosts

**Comment by theodotos** [comment]
Thanks @mfominov. I'll give it a try.
