### ISSUE TITLE
Titles on Gauges in Latest Version Broken

### ISSUE THREAD

**Issue by frajdej** [rfrail3/grafana-dashboards#61]
Hello,

I am having a weird issue with the titles on the gauges. A Grafana instance with an older version of Node Exporter doesn't seem to have this issue. There's a screenshot at the link below:

https://snipboard.io/Iao1qX.jpg

Let me know if any more information is needed.

**Comment by debian-d** [comment]
I am having the same issue. Only way that I could get the title to go away was to go down to v15. I tried to do down in node exporter versions as well, did not have any different results. 

@frajdej if you could tell me what version of prometheus and node-exporter you're using to make the title go away it would be appreciated. Thanks.

**Comment by debian-d** [comment]
I figured out how to fix it. If you go to overrides under the editor on the right side, and then filter by field, then select "display name" for the override policy, it will blank it out since it will try to change the name to a blank value. This lets it to full screen.

**Comment by frajdej** [comment]
Looks like Grafana is currently working on a fix that will be in the 7.1.2 release
