### ISSUE TITLE
Axes and labelling for disk I/O graphs

### ISSUE THREAD

**Issue by candlerb** [rfrail3/grafana-dashboards#70]
(relates to #58)

Some of the disk I/O graphs would benefit from more accurate Y-axis labels, units, and/or titles.  I have put the background info in this article:
https://brian-candler.medium.com/interpreting-prometheus-metrics-for-linux-disk-i-o-utilization-4db53dfedcfc

Ideally the stats would align with what "iostat" reports - I can prepare a PR if you like.

**Comment by candlerb** [comment]
This might be a bit tricky to do as I'm on a newer version of grafana (7.3.7) than the one in the repo (6.7.3) - and the export includes quite a lot of differences due to Grafana adding new fields.

Anyway, I've put my version up temporarily at https://psg.com/~brian/ne1860-1611854721829.json

The main changes I made were:
- set the axis labels and units for queue size and time spent doing I/O
- fix the disk read/write time queries to match what iostat does to generate r_await and w_await: e.g. `irate(node_disk_read_time_seconds_total{instance="$node",job="$job"}[5m]) / irate(node_disk_reads_completed_total{instance="$node",job="$job"}[5m])`
- change to SI units on summary "I/O Usage Read / Write" graph to be consistent with "Disk R/W Data"
- add descriptions to all the detail graphs based on the `iostat(1)` manpage

Adding average request size graphs (rareq-sz and wareq-sz) might be useful too, but I didn't do that.

**Comment by rfrail3** [comment]
Brian, excellent article, in depth and concise research, it was a pleasure to see all that information in one place, congratulations.

I just upload an update revision of the dashboard with Grafana 7.3.7.

Please, feel free to send a PR with the updates that you consider opportune, it'll be wellcome.

**Comment by rfrail3** [comment]
Brian, It's difficult to get a clear diff with the changes between your version and the current one. On commit a154f92 I upload the ones that I found, I think that these are all and it's all done.

**Comment by lethargosapatheia** [comment]
@candlerb As I don't have a medium account, I'd like to thank you here :) Really helped me out especially in regards to r_await and w_await - I was using them wrongly without the "completed" metrics. The io depth explanation was also very insightful.
