### ISSUE TITLE
Make resolution consistent (not mixture of 1/2 and 1/4)

### ISSUE THREAD

**Issue by candlerb** [rfrail3/grafana-dashboards#71]
In node-exporter-full, some graphs have resolution 1/4 (which really hides important detail) and some have resolution 1/2; sometimes even mixed on the same graph.

![image](https://user-images.githubusercontent.com/44789/106179454-f8aae180-6192-11eb-9a0d-5ce204f9d9dd.png)

Personally I'd prefer 1/1, but I can understand people wanting a faster draw time with 1/2.  However if that's the case, it would still be better to make it 1/2 consistently everywhere.

I can't quite work out what's going on in the JSON.  Some items have a small step, and some huge:

```
$ grep '"step"' node-exporter-full.json  | sort | uniq -c
   2               "step": 2
   1               "step": 20
  82               "step": 240
 107               "step": 4
   4               "step": 480
   9               "step": 8
   1           "step": 1800
  14           "step": 240
  11           "step": 900
```

**Comment by rfrail3** [comment]
I think that 1/2 could be a good balance.

About the steps, it's something that I miss completely until now.

Could you send a PR with the fixes?
