### ISSUE TITLE
datasource named ${DS_LOCAL} was not found

### ISSUE THREAD

**Issue by sailing0505** [rfrail3/grafana-dashboards#8]
I'm new to Grafana. when I import the file, I got following error. 
![image](https://user-images.githubusercontent.com/865959/33539781-fd67f0da-d902-11e7-84bb-87ec35106188.png)

**Comment by billmcnamara** [comment]
Check the settings icon > Datasources and verify/add a Prometheus source.

**Comment by youurayy** [comment]
what worked for me: 
1. replace the `__input` with `annotations/list...` (take from any of your other dashboards)
2. remove all `datasource:` refs
