### ISSUE TITLE
parse error: missing unit character in duration

### ISSUE THREAD

**Issue by derekakelly** [rfrail3/grafana-dashboards#80]
Hello,
About half of the sections are coming up like this.
![image](https://user-images.githubusercontent.com/5824837/119607921-257aa880-bdc3-11eb-9a6a-296ea67c8bc4.png)

I'm using Ubuntu 21.04, with Prometheus version 2.22.0+ds-1, and prometheus-node-exporter version 1.1.0+ds-2. Both installed with apt. I have Grafana version 6.7.4, installed with snap.

I had this dashboard working on another install, but it's fighting me a bit here.

**Comment by bjolivot** [comment]
the problem for grafana6 is the use of $__rate_interval, only availlable in grafana 7+

As a workaround, you can edit the json source and replace :
 - rate -> irate
 - $__rate_interval -> 5m

10 second in notepad++ :

open the json file
use the replace function with regex :
search: rate\((.*)\$__rate_interval
replace by: irate\(${1}5m

copy the json to grafana and enjoy this great dashboard (thank you @rfrail3 👍 )

**Comment by p6002** [comment]
Any way how to fix it in new Grafana?

**Comment by tadavid-cae** [comment]
any fix for  grafana/grafana-oss:9.2.6?

**Comment by p6002** [comment]
From what I've found online, these are the wrong Variables. 
Go into settings/variables and they should all be with a green checkmark, and the missing ones will show up if you click the link at the bottom. 

What I did was that I found a partially working dashboard, added the necessary panels from other dashboards to it and copied variables from them.

Some variables are repeated, such as job or node. Then I rename the variable to job2 and node2 in the dashboard settings and later in editing the panel, replace $job with $job 2 in the code and everything works.
Here a sample code:
`node_memory_MemFree_bytes{job="$job2",instance=~"$node2:$port",job=~"$job2"}`
Original code:
`node_memory_MemFree_bytes{job="$job",instance=~"$node:$port",job=~"$job"}`
