### ISSUE TITLE
[haproxy] Active Sessions panel should not be using rate()

### ISSUE THREAD

**Issue by szook** [rfrail3/grafana-dashboards#83]
in the haproxy-2-full.json file on the "Active Sessions" panel,  the `haproxy_frontend_current_sessions` and `haproxy_backend_current_sessions` metrics are "gauge" metrics rather than "counter", so applying the rate() function obfuscates the data.

I suggest changing these to something like:
```
sum(haproxy_frontend_current_sessions{proxy=~"$frontend",instance="$host"}) by (instance)
```

**Comment by rfrail3** [comment]
You are right, thanks for it Szook.
