### ISSUE TITLE
Disk average wait times negative axis fix

### ISSUE THREAD

**Issue by morganchristiansson** [rfrail3/grafana-dashboards#93]
Disk average wait times negative axis is not working

The negative-Y series transform regexp
https://github.com/rfrail3/grafana-dashboards/blob/f6580d47a121aa383bfda8ad0fd64afb0bec1257/prometheus/node-exporter-full.json#L8212

does not match the name generated fromlegend format
https://github.com/rfrail3/grafana-dashboards/blob/f6580d47a121aa383bfda8ad0fd64afb0bec1257/prometheus/node-exporter-full.json#L8305

Fixed with  `"alias": "/.*r_await.*/"`.

But maybe legend format should have nicer name than r_await instead? `"legendFormat": "{{device}} - Read wait time avg"` ?

**Comment by rfrail3** [comment]
It looks fine with the nice name.

Tahnks,
