### ISSUE TITLE
Update Dashboard on grafana.com

### ISSUE THREAD

**Issue by JsBergbau** [rfrail3/grafana-dashboards#98]
Hallo @rfrail3,

I've installed your Dashboard from Grafana.com https://grafana.com/grafana/dashboards/1860
However the latest changes aren't there yet, especially the new variable value `[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+` for the diskdevice on Raspberry PI

Could you please also update on Grafana.com? Would be great.

Thank you very much.

**Comment by rfrail3** [comment]
Hello @JsBergbau,

I just updated the dashboard on Grafana.com, check the revision 26.

Thanks,

**Comment by JsBergbau** [comment]
Thank you for your fast action. Works now.
